version: "3.9"

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "${PG_PORT}:${DB_PORT}"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin"]
      interval: 5s
      timeout: 10s
      retries: 5
