# Generated by Django 5.0.4 on 2024-07-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='user_id',
            new_name='user',
        ),
    ]
