# Generated by Django 5.0.4 on 2024-07-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_albums_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_id', models.IntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.albums')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('s3_url', models.CharField(max_length=255)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.albums')),
            ],
        ),
    ]
