# Generated by Django 5.0.4 on 2024-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_networks_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='album_id',
            new_name='album',
        ),
    ]
