# Generated by Django 5.0.4 on 2024-08-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='s3_url',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='s3_url',
            new_name='file_name',
        ),
    ]
